### ISSUE TITLE
Add more formulas

### ISSUE THREAD

**Issue by ArcticWaffles** [ArcticWaffles/BandNameGenerator#8]
The band names are starting to look similar pretty quickly. Add variety with more formulas.

**Comment by JVimes** [comment]
Also, randomize the first formula pick, but then cycle through them after that.

And do we need to seed the random number generator with the system clock so it doesn't generate the same sequence every run?

**Comment by ArcticWaffles** [comment]
Thanks, good ideas! Actually, it looks like the default Random() constructor does use a system-generated seed that is time-based so it generally shouldn't produce the same sequence unless the objects are created within [15 milliseconds ](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=net-5.0#Instantiate)of one another.  

Did some quick testing to verify that I'm getting different sequences, and things look good!

But I do think I'll make the random object a class member instead of generating a new one each time, because that's the recommendation.

**Comment by ArcticWaffles** [comment]
Resolved with commit db576a1b.
